### ISSUE TITLE
Permission inheritance setting is ignored

### ISSUE THREAD

**Issue by sigdestad** [enonic/xp#7643] opened 2019-11-13 16:11 UTC
To recreate:
1. Edit a child item, remove "inherit permissions" and save
2. Now go to the parent item, and make changes to it's permissions

This will effectively overwrite the child item permissions, (without checking the "overwrite .." option).

NB! I have verified that this bug also exits in 6.15.3, and that by checking "overwrite .." child items actually get the "inherit" option set.

Conclusion, this must be a serious bug in the algorithm for applying permissions recursively. Whenever reaching an item with "inherit = false", the algorithm should not change the specific item, or any of it's children.

**Comment by GlennRicaud** [comment] 2019-11-13 20:53
It is working as originally designed. Not inheriting permissions from the parent does not mean it is not impacted by parent permissions. It will then try to merge the permissions as defined in the "Default merging strategy"
Exact same behaviour reproduced in XP 5.0

@alansemenov knows about the details also.
Closing this issue

**Comment by sigdestad** [comment] 2019-11-13 21:19
How can this be working as intended? Inherit = false does not mean "Inherit anyway". We will have to go through this together.

**Comment by sigdestad** [comment] 2019-11-13 22:27
So, I have tested some more, and believe I understand "how" things are working right now. 
I'll summarize it as follows:
* When you edit an item (after clicking don't inherit) all your changes are saved and stored, including the "don't inherit" value. So, for instance I store "read -> deny" for a child item
* When I later edit the same entry on a parent, child's read-deny settings are kept, but new values (for instance write = true) are added.

However, if I remove a permission, i.e. Groupx = read on child, then go back to parent and modify Group x, it will suddenly re-appear on the child item.

The idea here is basically, you may step into the tree structure and do stuff (after clicking inherit = false), but permissions are generally still inherited. Which is very confusing, and not logical.

We have to decide how to handle this.

IMHO: "Inherit = false"  indicates a full detach from the tree structure, i.e. any change to a parent item should not propagate (at least by default)
The current mode is more like a "modifying" the inheritance thing (not turning it off). Actually, using deny works perfectly for this stuff. However, it is not entirely consistent, since I am able to remove a permission row, and it will suddenly re-appear if a parent makes a change to it. So, in this mode, I should simply not be able to remove a row, but maybe rather choose "Deny all" setting etc?

To conclude:
* We can make improvements to make the current stuff work better (both UI and storage-wise I assue?). 
** I.e. add a "Deny all" permission dropdown, and replace the "inherit checkbox" with a lock icon (unlock to make changes)
** Prevent removal of rows that are inherited (only allow removal of locally added rows)
* Later, we could also support a "inherit = none" option or something like that, where permissions are completely detached from the parent item.
** After "unlocking" to edit the item, we could also provide user with a "cancel inheritance" option, allowing user to also remove inherited rows. NB! In this mode, The user should not be able to specify "deny" permissions, as they are not relevant.

Phuh..

**Comment by sigdestad** [comment] 2019-11-13 22:31
It is better to talk about inherit = all" than "true" I guess.

**Comment by sigdestad** [comment] 2019-11-13 23:15
I have concluded the biggest problem is the UI, but we still need to make some minor improvements to the back-end. I.e. one can currently remove a permission row, but this is not "working", since any change to a parents permissions will "re-introduce" the row in the child.

As such, we should instead prevent support for removing of rows, both in UI and back-end/API. So, if you try to remove it, it should just be returned in the result. Possibly, with all permissions set to "deny"? Rows that do not exist in parent can safely be removed ofcourse.

**Comment by alansemenov** [comment] 2019-11-14 08:32
Below is the comment (from 2014) from the [backend class](https://github.com/enonic/xp/blob/master/modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/DefaultPermissionsMergingStrategy.java) implementing the current "merging" strategy in case of when "Inherit permissions" is off. 5 years ago this was definitely intended behaviour, no one touched it since. This doesn't mean it's _correct_ behaviour, but definitely not a bug. Also, the fact that this behaviour is not documented in our docs is mindblowing. It just shows that most of our customers are not using this feature at all, it's super counter-intuitive.

```
/**
 * Default merging strategy:
 * <p>
 * Include all permissions that are in only one of the two ACLs, without modification.
 * For entries in both ACLs, merge according to the following rules:
 * - If permission is set in child entry, use the value from the child entry
 * - Otherwise if permission is set in parent entry, use the value from the parent entry
 * - Otherwise leave permission unset
 * <p>
 * Example:
 * Parent: user1[+create, -modify, -publish],          user2[+create, -modify]
 * Child : user1[+create, +modify, -delete],           user3[+create, -modify]
 * ------------------------------------------------------------------------------------------------------
 * Result: user1[+create, +modify, -delete, -publish], user2[+create, -modify], user3[+create, -modify]
 */
```

**Comment by alansemenov** [comment] 2019-11-14 11:36
Closing this, since we decided to solve this with changes in the UI. We should create a separate task for enabling separate update of permissions in the index.

**Closed by alansemenov** 2019-11-14 11:36 UTC
Labels: Bug
