### ISSUE TITLE
PageComponentsView not masked when SiteConfiguratorDialog open

### ISSUE THREAD

**Issue by ashklianko** [enonic/xp#5310] opened 2017-07-10 10:01 UTC
Open PageComponentsView and then SiteConfiguratorDialog  - everything on page is masked except 
PageComponentsView 
![image](https://user-images.githubusercontent.com/4255706/28012868-db13aa44-656f-11e7-8341-2db6e8c2a841.png)

**Comment by alansemenov** [comment] 2017-07-12 14:28
Duplicate of #5326

**Closed** 2017-07-12 14:28 UTC
Labels: Bug, Not in Changelog
