### ISSUE TITLE
Jetty IgniteSessionDataStore

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#6100] opened 2018-03-01 11:08 UTC
Some other grid implementations (requires Jetty 9.4)

* Hazelcast: https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-hazelcast/src/main/java/org/eclipse/jetty/hazelcast/session/HazelcastSessionDataStore.java

* Redis: https://github.com/cloudbees/jetty-redis/blob/master/src/main/java/com/cloudbees/jetty/session/redis/RedisSessionDataStore.java

* Google Cloud: https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-gcloud/jetty-gcloud-session-manager/src/main/java/org/eclipse/jetty/gcloud/session/GCloudSessionDataStore.java

**Comment by aro** [comment] 2018-06-08 10:38
Duplicate of #6229

**Closed by aro** 2018-06-08 10:38 UTC
