### ISSUE TITLE
Regexp in site config is not validated on save

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#9465] opened 2022-05-04 20:19 UTC
With this site.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<site xmlns="urn:enonic:xp:model:1.0">
  <form>
    <input name="url" type="TextLine">
      <label>URL</label>
      <occurrences minimum="0" maximum="1"/>
      <config>
        <regexp>^http(s)?:\/\/.?(www\.)?[a-zA-Z0-9][-a-zA-Z0-9@:%._\+~#=]{0,255}\b([-a-zA-Z0-9@:%_\+.~#?&amp;//=]*)</regexp>
      </config>
    </input>
  </form>
</site>
```

XP won't give any errors when URL `https://www.oslo.kommune.no/barnehage/finn-barnehage-i-oslo/#!c%7Cf_preschool_type_student/c.f_preschool_type_student//m.list` is saved in the input field. However, the site is correctly shown as invalid after save.

**Comment by rymsha** [comment] 2022-08-09 12:50
Duplicate of #9464 ?

**Comment by anatol-sialitski** [comment] 2022-08-11 11:04
@alansemenov how I can see that is expected behavior. 
The things is Content Studio sends a request with `requireValid=false`, therefore on the UI  errors don't appier and a content is saved as invalid.
If you want to show errors on the UI, I can suggest to use combination of the fields `isValid` and `validationErrors` from the response.

**Comment by rymsha** [comment] 2022-08-17 08:04
It is not a bug of XP. Should be fixed in CS, if needed.

**Closed by rymsha** 2022-08-17 08:04 UTC
Labels: Bug, Won't Fix
