### ISSUE TITLE
HtmlLinkProcessor: correctly process links with query parameters

### ISSUE THREAD

**Issue by ashklianko** [enonic/xp#7571] opened 2019-10-23 13:44 UTC
Links like ~`content://123456#insert-tab` or `content://123456?a=1&b=2`~ `content://<id>?query=<query>&fragment=<fragment>` should be correctly resolved.

`<query>` - `encodeuricomponent("key1=value1&key2=value2")` - value will be decoded and added to resulting link as query. If decoded string contains any invalid query symbols the entire query will be ignored.

`<fragment>` - `encodeuricomponent("some-fragment")` - value will be decoded and added to resulting link as fragment. If decoded string contains any invalid fragment symbols the entire fragment will be ignored.

resulting url will be (based on exampples)
`http://bla-bla-bla?key1=value1&key2=value2#some-fragment`

**Comment by rymsha** [comment] 2020-01-09 20:00
duplicate of #7035 ?

**Comment by alansemenov** [comment] 2020-09-16 07:41
https://discuss.enonic.com/t/anchor-link-in-the-link-dialog-box/2298

**Comment by alansemenov** [comment] 2020-09-16 07:42
Client-side validation task: https://github.com/enonic/app-contentstudio/issues/1458

**Comment by alansemenov** [comment] 2020-09-16 07:44
We also need a task in Content Studio for adding a new field on the "Content" tab for whatever will be appended to the content url (hash, params etc.)

**Comment by rymsha** [comment] 2022-06-22 16:23
Also occupying query params and anchor in content urls "just" for direct transfer to http urls is probably  squander

**Comment by alansemenov** [comment] 2022-06-23 07:18
NB! UI will url encode values in the anchor & query string fields before saving them.

**Comment by rymsha** [comment] 2022-06-23 08:25
NB! Doing it just in UI is not secure enough.

**Comment by larserikpedersen** [comment] 2022-06-23 08:29
Hi Sergey

Am I supposed to receive these, or is it meant for another Lars Erik?


Med vennlig hilsen

Lars Erik Pedersen
innholdsredaktør
avdeling utvikling og digitale kanaler
divisjon digitalisering og helseregister
mobil: 466 73 423

***@***.***

Postadresse: Pb 220 Skøyen, 0213 Oslo
Besøksadresse: Vitaminveien 4, 0483 Oslo
https://helsedirektoratet.no<https://helsedirektoratet.no/>  https://helsenorge.no/

P Tenk på miljøet; ikke skriv ut denne e-posten hvis det ikke er helt nødvendig



Fra: Sergey Rymsha ***@***.***>
Sendt: torsdag 23. juni 2022 10:25
Til: enonic/xp ***@***.***>
Kopi: Lars Erik Pedersen ***@***.***>; Manual ***@***.***>
Emne: Re: [enonic/xp] HtmlLinkProcessor: correctly process links with anchor and query parameters (#7571)


NB! Doing it just in UI is not secure enough.

**Closed** 2022-07-12 12:23 UTC
Labels: Improvement
