### ISSUE TITLE
Implement error handler for /admin*

### ISSUE THREAD

**Issue by sigdestad** [enonic/xp#7349] opened 2019-09-03 05:18 UTC
When accessing the admin console, if you for any reason get the error page (i.e. access something without permissions) we currently get the default error handler and a not-so-nice stack trace.
Implement an error handler that will display the error code and message in a controlled way!

**Comment by alansemenov** [comment] 2019-11-27 09:26
Need design of the page

**Comment by rymsha** [comment] 2020-09-25 07:51
Duplicate of #8375

**Closed by rymsha** 2020-09-25 07:51 UTC
Labels: Improvement
