### ISSUE TITLE
OptionSet content: incorrect validation of the content in the grid, when required option was removed 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4593] opened 2017-03-13 08:42 UTC
1. Select 'Features' and open a wizard for the OptionSet content
2. select the Option2 in the 'single selection'
3. click on the Option3 in the multi selection and upload an image (see the first screenshot). Save the option-set
4. navigate to the grid and delete the just uploaded image
BUG: when the image was deleted, required input is getting empty, so the  OptionSet should be displayed with red icon(in the grid)
![step1](https://cloud.githubusercontent.com/assets/3728712/23847018/6efe9e2c-07e1-11e7-804e-4b9a5125e739.png)
![result](https://cloud.githubusercontent.com/assets/3728712/23847163/291d017c-07e2-11e7-9be1-106aac3a5152.png)

**Comment by alansemenov** [comment] 2017-03-21 09:45
@edloidas both bugs related to option sets must be fixed before release of 6.10, so no refactoring here, please - no time for this now.

**Comment by edloidas** [comment] 2017-03-24 08:59
I'm not actually sure, that we need to change the current behavior. When we remove the image, we do not check the validity of the parent content in that way. If you open the parent content, it will try to load the image by reference and discover, that the image was removed, suggesting to save the content and remove the reference automatically. When the reference will be removed, the content became invalid, because there is no reference. So, the invalidity of the content is caused by the absent reference, not absent content by that reference. Though content is marked as invalid in wizard because of the check in image selector.

**Comment by alansemenov** [comment] 2017-03-24 09:10
@edloidas It's the same principle that we have in Image Selector, for example, or any other content selector. Create an image selector, upload a required image and then delete the image directly from the grid. The image selector will be instantly invalidated in the wizard. It should work the same for option sets.

**Comment by edloidas** [comment] 2017-03-24 09:36
Yes, and it works for option sets (in wizard). But we are talking about the invalidation in the grid. It doesn't work for Image Selector or any other content either.

**Comment by alansemenov** [comment] 2017-03-24 11:04
Ah, then I misunderstood. No, it's fine the way it is.

**Closed** 2017-03-27 11:10 UTC
Labels: Bug, Won't Fix
