### ISSUE TITLE
Forbid leading `-` in project name

### ISSUE THREAD

**Issue by vbradnitski** [enonic/xp#8136] opened 2020-06-05 15:21 UTC
initial spec allows `-` #7281

**Comment by alansemenov** [comment] 2020-06-05 15:30
@vbradnitski can you fix trailing `-` as well?

**Comment by rymsha** [comment] 2020-06-05 16:19
I take this one.

**Comment by sigdestad** [comment] 2020-06-05 17:33
Maybe forbid symuch chars alltogether?

**Comment by rymsha** [comment] 2020-06-07 19:28
Collecting info (no conclusion yet)

Project creates repository. ProjectName should have same or stricter pattern 
of Current RepositoryId ([a-z0-9\\-:])([a-z0-9_\\-\\.:])*"

RepositoryId is also limited by Elasticsearch index name rules
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html#indices-create-api-path-params

**Comment by rymsha** [comment] 2020-06-07 21:06
Elasticsearch reserves `-` as a first character

> Cannot start with -, _, +

Usually it is done to eliminate confusion with command line arguments.
(Call repo `-rf` and wait for unsafe script to execute `rm` on it)

`-` not allowed anywhere is overkill. People want it: 
`blog-no`, `blog-en`

Trimming it on end would also unreasonably limit some use cases, but without `+` allowed it is not as convenient as it could be.
Still I don't want to complete regexp too much.

**Comment by sigdestad** [comment] 2020-06-07 21:31
Also, if we will concat layer+project name, the names need a strict char limit

**Comment by rymsha** [comment] 2020-06-08 06:14
Related issue explains why `:` was excluded from projectName #6777
We have a separate issue about length #8113

**Comment by rymsha** [comment] 2020-06-08 09:59
It is not a bug. It is a feature. we well passed that line when we can introduce such changes in 7.3
We certainly need to reconsider allowed characters in identifiers, but it we have an issue about it already #6777 and it is for 8.0 milestone.
Marks a won't fix.

**Comment by sigdestad** [comment] 2020-06-08 11:30
Is limiting chars a feature? Spending 10 minutes to fix this now, or a week of upgrade scripts and other problems trying to mitigate this when layers are implemented?

**Comment by rymsha** [comment] 2020-06-08 11:40
"Fix" will introduce more inconsistencies between project and repository names.
It also does changes behavior in a way that all `sanitize` functions written (in lib, or CS) will most likely break. Fix it requires all requires good coordination between lib-common, CS and XP code and well above your estimate.

**Comment by sigdestad** [comment] 2020-06-08 11:45
I am happy if we only implement this limit in back-end right now. (just to avoid upgrade future upgrade scripts). Don't understand what you mean by "introducing more inconsistencies between project and repo name" by limiting number of chars for project?

**Comment by rymsha** [comment] 2020-06-08 11:45
But I'm ready to reopen it, I still want it to be fixed badly.
If we are fine spending more than 10 minutes on this.

**Comment by sigdestad** [comment] 2020-06-08 11:46
Let's fix it, but only back-end, then leave a task for UI and more in upcoming releases.

**Comment by sigdestad** [comment] 2020-06-08 11:46
What would be a reasonable limit BTW?

**Comment by alansemenov** [comment] 2020-06-08 11:53
> Don't understand what you mean by "introducing more inconsistencies between project and repo name" 

What @rymsha means I guess is that we've never had any character/length limitations for repository name for example [here](https://developer.enonic.com/docs/xp/stable/api/lib-repo#create). If we introduce it only for projects, this will be an inconsistency between repository and project.

**Comment by sigdestad** [comment] 2020-06-08 12:01
I see, but for repo's the limit is defined by ES anyway right? Projects are a very specific subset of this which does not make it an "inconsistency" imho - the limit is actually to prevent inconsistency.

**Closed** 2020-06-16 12:15 UTC
Labels: Not in Changelog
