### ISSUE TITLE
main.js won't even make a simple log entry

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#8907] opened 2021-06-21 07:02 UTC
Example repo
https://github.com/ComLock/mainjs

https://github.com/ComLock/mainjs/blob/main/src/main/resources/main.js

```javascript
const libCluster = require '/lib/xp/cluster';
log.info(`Starting ${app.name} ${app.version} isMaster:${libCluster.isMaster()} config:${JSON.stringify(app.config, null, 4)}`);
__.disposer(function() {
	log.info(`Stopping ${app.name} ${app.version} isMaster:${libCluster.isMaster()} config:${JSON.stringify(app.config, null, 4)}`);
});
```

Tested using Enonic XP 7.6.1

**Comment by ComLock** [comment] 2021-06-21 07:12
It looks like it works when I remove isMaster

**Comment by rymsha** [comment] 2021-06-21 07:45
duplicate of #8844

**Closed** 2021-06-21 15:20 UTC
