### ISSUE TITLE
lib task cancel/stop method

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#4881] opened 2017-04-27 13:23 UTC
Is it possible to cancel a task without restarting the Enonic XP server?

Or perhaps we need that functionality?

**Comment by srs** [comment] 2017-05-05 08:14
I think this should be possible. @aro?

**Comment by aro** [comment] 2017-05-05 08:39
We do not currently have a cancel function. I think it would be quite simple to implement it.

What I do now is to set some kind of cancel flag that is a private variable in the library. Then check the flag inside some loop in the task callback, so it can stop the task gracefully if requested.

Something like this:

```javascript
var taskId;
exports.launchTask = function () {
    taskId = taskLib.submit({
        description: 'My task',
        task: function () {
            var id = taskId;
            while (taskId === id) {
                // do something
            }
        }
    });
};

exports.cancelTask = function () {
    taskId = null;
};

```

But this will not interrupt all kinds of execution, just when checked in the callback code.
Also this is not cluster-safe.

**Comment by srs** [comment] 2017-05-05 09:46
Let's discuss how we could do this.

**Comment by alansemenov** [comment] 2018-10-17 08:14
Is this still something we want to do? I think it looks fairly simple but we need a ``stoppable`` flag for a task to prevent cancelling tasks like publishing and deletion.

**Comment by sigdestad** [comment] 2018-10-17 10:46
We should keep this in the backlog, in terms of publishing the problem is really more of a "transaction" issue. Stopping tasks would normally not be done unless there are issues - one would never provide a "stop" action for publishing in the UI imho

**Comment by ComLock** [comment] 2018-11-01 07:42
Lets say for some reason one has an endless loop inside a task, this task then will continue "forever" consuming resources. Even when you stop the app, the task will continue running. In fact you will have to stop the Enonic XP server in order to kill the task. This is not a good situation in Production.

**Comment by ComLock** [comment] 2018-11-12 10:36
As a workaround I will use the taskName or taskId as the name for a node and write stop to that node. Then in the task loop I will check that node. This could potentially also be used for pause and resume (seperate loop with checknode sleep).

Depending upon how efficient it is to read a node versus calculating how long since last checked the node, I could check the node each iteration or some smart delay.

**Comment by alansemenov** [comment] 2020-04-29 09:07
We'll leave it with your way of solving the issue.

**Closed by alansemenov** 2020-04-29 09:07 UTC
Labels: Feature
