### ISSUE TITLE
Passing in maxAge when doing system dumps results in NullPointerException

### ISSUE THREAD

**Issue by gbbirkisson** [enonic/xp#8108] opened 2020-05-22 10:13 UTC
> Note: This happens even if archive not true

Running:

```
curl --header "Content-Type: application/json"   --request POST   --data '{"name":"test","includeVersions":true,"maxVersions":10,"maxAge":1}' http://user:pass@localhost:4848/system/dump
```

Results in:

```
java.lang.NullPointerException: null
	at com.enonic.xp.repo.impl.index.IndexFieldNameNormalizer.doNormalize(IndexFieldNameNormalizer.java:16)
	at com.enonic.xp.repo.impl.index.IndexFieldNameNormalizer.normalize(IndexFieldNameNormalizer.java:9)
	at com.enonic.xp.repo.impl.elasticsearch.query.translator.resolver.StoreQueryFieldNameResolver.appendIndexValueType(StoreQueryFieldNameResolver.java:24)
	at com.enonic.xp.repo.impl.elasticsearch.query.translator.resolver.AbstractQueryFieldNameResolver.createValueTypeAwareFieldName(AbstractQueryFieldNameResolver.java:82)
	at com.enonic.xp.repo.impl.elasticsearch.query.translator.resolver.AbstractQueryFieldNameResolver.resolve(AbstractQueryFieldNameResolver.java:62)
	at com.enonic.xp.repo.impl.elasticsearch.query.translator.resolver.StoreQueryFieldNameResolver.resolve(StoreQueryFieldNameResolver.java:9)
	at com.enonic.xp.repo.impl.elasticsearch.query.translator.factory.FilterBuilderFactory.createRangeFilter(FilterBuilderFactory.java:175)
	at com.enonic.xp.repo.impl.elasticsearch.query.translator.factory.FilterBuilderFactory.doCreateFilterBuilder(FilterBuilderFactory.java:97)
	at com.enonic.xp.repo.impl.elasticsearch.query.translator.factory.FilterBuilderFactory.appendFilters(FilterBuilderFactory.java:77)
	at com.enonic.xp.repo.impl.elasticsearch.query.translator.factory.FilterBuilderFactory.doCreate(FilterBuilderFactory.java:54)
	at com.enonic.xp.repo.impl.elasticsearch.query.translator.factory.FilterBuilderFactory.create(FilterBuilderFactory.java:47)
	at com.enonic.xp.repo.impl.elasticsearch.query.translator.factory.QueryBuilderFactory.create(QueryBuilderFactory.java:49)
	at com.enonic.xp.repo.impl.elasticsearch.query.translator.NodeVersionQueryTranslator.createQueryBuilder(NodeVersionQueryTranslator.java:56)
	at com.enonic.xp.repo.impl.elasticsearch.query.translator.ESQueryTranslator.doTranslate(ESQueryTranslator.java:65)
	at com.enonic.xp.repo.impl.elasticsearch.query.translator.ESQueryTranslator.translate(ESQueryTranslator.java:41)
	at com.enonic.xp.repo.impl.elasticsearch.executor.SearchExecutor.execute(SearchExecutor.java:35)
	at com.enonic.xp.repo.impl.elasticsearch.search.SearchDaoImpl.search(SearchDaoImpl.java:23)
	at com.enonic.xp.repo.impl.search.NodeSearchServiceImpl.query(NodeSearchServiceImpl.java:81)
	at com.enonic.xp.repo.impl.node.FindNodeVersionsCommand.execute(FindNodeVersionsCommand.java:27)
	at com.enonic.xp.repo.impl.node.NodeServiceImpl.findVersions(NodeServiceImpl.java:696)
	at com.enonic.xp.repo.impl.dump.RepoDumper.getVersions(RepoDumper.java:354)
	at com.enonic.xp.repo.impl.dump.RepoDumper.dumpVersions(RepoDumper.java:170)
	at com.enonic.xp.repo.impl.dump.RepoDumper.lambda$execute$2(RepoDumper.java:106)
	at com.enonic.xp.context.ContextImpl.runWith(ContextImpl.java:86)
	at com.enonic.xp.repo.impl.dump.RepoDumper.execute(RepoDumper.java:106)
	at com.enonic.xp.repo.impl.dump.DumpServiceImpl.dump(DumpServiceImpl.java:245)
	at com.enonic.xp.impl.server.rest.task.DumpRunnableTask.run(DumpRunnableTask.java:45)
	at com.enonic.xp.impl.task.TaskWrapper.lambda$callTaskWithContext$0(TaskWrapper.java:90)
	at com.enonic.xp.context.ContextImpl.callWith(ContextImpl.java:102)
	at com.enonic.xp.impl.task.TaskWrapper.callTaskWithContext(TaskWrapper.java:89)
	at com.enonic.xp.impl.task.TaskWrapper.doRun(TaskWrapper.java:75)
	at com.enonic.xp.impl.task.TaskWrapper.run(TaskWrapper.java:59)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by rymsha** [comment] 2020-05-22 10:23
It seems like duplicate of #5239

**Comment by vbradnitski** [comment] 2022-09-07 08:07
Can't reproduce

**Comment by rymsha** [comment] 2022-09-12 13:01
It is now reproduced

**Comment by rymsha** [comment] 2022-09-12 13:03
- The bug is in `RepoDumper` - it forgets to set filed name in repo filter.
- Actually all FieldFilter instances should require filed name (should also be fixed)

**Closed** 2022-09-20 11:56 UTC
Labels: Bug
