### ISSUE TITLE
Event listeners may block event dispatching

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6670] opened 2018-10-18 07:36 UTC
Events are dispatched sequentially with a single thread. That makes that an event listener function may block all event dispatching in the system.

Original issue:

----
Event listeners in main.js and in tasks are affected by sleep in main.js

The code below should produce the following log:
send
got
send
got
send
got
send
got
send
got

It actually produces:
send
send
send
send
send
got
got
got
got
got

```javascript
lib.event.listener({
	type: 'custom.*',
	callback: (event) => {
		log.info(toStr({gotEvent: event}));
	}
});
for (let i = 0; i < 5; i += 1) {
	lib.task.sleep(2000);
	const event = {
		type: 'whatever',
		distributed: false, // Send only to current cluster node.
		data: {
			a: 1
		}
	};
	log.info(toStr({sendingEvent: event}));
	lib.event.send(event);
}
```

I will try a workaround by making the listener start inside a task.

**Comment by ComLock** [comment] 2018-10-18 07:45
I tried both workarounds.

Running the sleep+send as a task worked beautifully.

However

Running the listener in a task, while the sleep+send in the main.js still affected the listener.

**Comment by ComLock** [comment] 2018-10-18 07:46
So current lesson is: "Do not sleep in main.js thread"

**Comment by ComLock** [comment] 2018-10-22 12:04
Notice that when sleeping in main, Content Studio doesn't show new content before reload.

**Comment by aro** [comment] 2018-10-22 12:28
I reproduced the issue. Looks like a sleep in an application's main.js blocks all the events sent in the system, even though the events should be asynchronous.

**Comment by alansemenov** [comment] 2018-11-23 13:15
@aro @GlennRicaud what happened to this one? there's a PR but the issue was moved from "Review" to "In progress"

**Comment by GlennRicaud** [comment] 2018-11-23 13:18
Well it was good but after discussion we wanted to do more. Thus the sprint focus about events.

**Comment by alansemenov** [comment] 2018-11-26 11:57
Let's merge this and then create additional tasks later

**Comment by GlennRicaud** [comment] 2020-02-05 08:56
Reassigning to @rymsha as he has been working on related problems and has planned to refactor it in the future.

**Comment by rymsha** [comment] 2020-02-05 12:31
`sleep` must be avoided by any means. It doesn't fit in JS world. I'm discussing deprecation of this library with @sigdestad

**Comment by GlennRicaud** [comment] 2020-02-05 12:58
Not really about the sleep. More about event listener blocking the entire event propagation I think.

**Comment by rymsha** [comment] 2020-04-16 11:27
#8021 gives little bit more input which areas are affected

**Comment by rymsha** [comment] 2020-04-21 08:36
Current event flow diagram
![XPEvents](https://user-images.githubusercontent.com/2891483/79844297-c5455600-83bb-11ea-84bf-1f52d264ee73.png)

**Comment by rymsha** [comment] 2020-04-21 09:29
"Just" giving more threads to EventDispatcher would introduce a lot of issues where events will "reorder" - for instance node.renamed may arrive before node.created we already observe such behavior in clustered environment #7990

**Comment by rymsha** [comment] 2020-05-04 20:47
#8083 takes over this issue, but provided example demonstrates correct behaviour. Developer must ensure that main.js finishes. Events generated by main.js won't be executed concurrently with main.js itself.

**Closed by rymsha** 2020-05-04 20:47 UTC
Labels: Bug, Won't Fix
