### ISSUE TITLE
Implement management of READ permissions for project content

### ISSUE THREAD

**Issue by ashklianko** [enonic/xp#7954] opened 2020-03-12 20:21 UTC
Backend part of:

@alansemenov commented on [Wed Mar 04 2020](https://github.com/enonic/app-contentstudio/issues/1586)

* Add a new wizard step called "Content"
* Inside add a radio-group labeled "Read access" with three buttons (none of them selected by default):
  - _Private_
  - _Public_
  - _Custom_
* Selection should be mandatory, otherwise project cannot be saved
* Localise all of the new phrases (step name, radio-group and button labels)
* Add Principal selector under "Custom", disabled by default
* When "Custom" is selected, enable the selector (and vice versa)
* If project is saved with "Custom" and no principals selected, it should be saved as "Private".
* Selected options should look like they do for principal selector inside Project Role wizard in the Users app:

![image](https://user-images.githubusercontent.com/11612490/75897479-e9af9800-5e38-11ea-8b13-41de69307e1c.png)

Radiogroup selection (and selected principals for Custom option) should be added to the Project data model on update.

![image](https://user-images.githubusercontent.com/11612490/75966271-59219800-5eca-11ea-9970-eaeabe4fd722.png)

**Comment by rymsha** [comment] 2020-03-14 07:12
There is one important thing which is not mentioned: "read access" only exists in JSON API. It must not exist in core API.

**Comment by sigdestad** [comment] 2020-03-14 07:14
Hmm, what do you mean?

**Comment by rymsha** [comment] 2020-03-14 07:17
I mean that project "read access" is synthetic sugar on top of content node access permissions

**Comment by rymsha** [comment] 2020-03-14 07:19
This is a duplicate of #7945 all discussions were there

**Comment by rymsha** [comment] 2020-03-14 07:28
Unfortunately suggested implementation https://github.com/enonic/xp/commit/6fd0118797717580cd7127a84cb03efa48210475 ignores discussions in #7945

**Comment by sigdestad** [comment] 2020-03-14 15:03
I thought project read access was handled through the "project roles" setting - and is not related to the node read permissions? Only users that have a role in the project should be able to access it. Node access combines the roles, and the read access part.

**Comment by rymsha** [comment] 2020-03-14 16:09
Screenshot suggests, it is about content permissions (thus node permissions), not about "project roles".

**Comment by sigdestad** [comment] 2020-03-14 18:34
Ah, screenshot is indeed wrong here.

**Comment by sigdestad** [comment] 2020-03-14 18:36
I fixed the title :-)

**Comment by alansemenov** [comment] 2020-03-16 14:28
I don't understand the purpose of this task. We already have a backend task to implement this: https://github.com/enonic/xp/issues/7945. Closing.

**Closed by alansemenov** 2020-03-16 14:28 UTC
