### ISSUE TITLE
Update text of notifications messages

### ISSUE THREAD

**Issue by pmi** [enonic/xp#6227] opened 2018-05-04 15:03 UTC
@sgauruseu commented on [Thu Apr 19 2018](https://github.com/enonic/app-contentstudio/issues/19)

@sgauruseu commented on [Mon Apr 09 2018](https://github.com/enonic/xp-apps/issues/754)

Currently we can see the next types of notification messages:

1. Content created       **actual**:  "Content created."      **expected**:   "Content is created."
2. Content Saved          **actual**:    ""display name" saved."     **expected** : The item is saved."
3. Content has been published **actual**:    "Item "/test" was published."    **expected**:   "The item is published."
4. Content has been unpablished  **actual**:     "Item "test" was unpublished."        **expected**: "The item is unpublished."
5.  Three items has been published **actual**:   "Published 3 items."     **expected**:  "3 items are published"

---

@pmi commented on [Thu Apr 26 2018](https://github.com/enonic/app-contentstudio/issues/19#issuecomment-384669657)

@alansemenov Is it a good idea to show less info than we can ? Also when operation results are mixed the message gets more complicated with further details.

**Comment by sigdestad** [comment] 2018-05-04 19:27
We need to go through these texts, things are not in sync here..
We should always call them "items", and need to agree what is correct for each sentence

**Comment by jsi** [comment] 2018-05-07 07:36
In case 1 and 5, the current message sounds much better than the suggestion in my ear.  For instance: "Content created" and "Content is created" say the exact same thing, but the former is simpler and therefore better.  Same argument for keeping "Published 3 items".  -  There is no reason why these kinds of messages from the system need to be grammatically correct sentences.

For case 2-4, I do think it is good to have as much info as possible, as long as the info is correct, but, like @sigdestad  say: We need to go through these texts and make sure they are in harmony with each other.  -  I volunteer to help out.  ;)

**Comment by pmi** [comment] 2018-05-07 07:44
Good points, guys ! 

Agree that messages were inconsistent.
We had a chat with @alansemenov and decided to show number in case of many items, and content name in case of 1 item in the message.

I have gone through them and added 'items' everywhere, as well as verified that content name is displayed (not id, not display name, not full path) in case of single item.

There are also cases when message gets even more complicated, i.e. some contents already exist at the destination and some contents failed to be moved. In that case message is going to look like:
_2 items were moved ( Already moved: "content1" ). Item "content2" was not found._

**Comment by alansemenov** [comment] 2018-05-14 07:52
@jsi  can you verify that texts are correct now? 

the operations that return notifications which we should test are: create, save, move, publish/unpublish, delete. for each type we need to perform an operation first with a single item, then with multiple. 

we also need to make sure that @sgauruseu updates the tests accordingly.

**Comment by jsi** [comment] 2018-05-14 13:38
From what I can tell in the PR, the texts look good.  However, I can not verify that this covers all necessary texts.  With that minor reservation, I approve of the changes that have been made!

**Comment by jsi** [comment] 2018-05-14 13:45
How about this issue: https://github.com/enonic/app-contentstudio/issues/64
Is it related?  Should it be fixed in the same context?

**Comment by alansemenov** [comment] 2018-05-14 13:51
No, that is a different problem (which I cannot reproduce, btw)

**Comment by jsi** [comment] 2018-05-14 14:00
@alansemenov Okay.  I will set this issue to "Done", but Siarhei reproduced app-contentstudio#64 today in tests, so it is still something we need to look at.  Pavel will take it after Feature Freeze.

**Closed** 2018-05-15 10:11 UTC
Labels: Improvement, Not in Changelog
