### ISSUE TITLE
Hit Elasticsearch Parent Circuit Breaker on customer installation

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#7290] opened 2019-08-12 13:05 UTC
On the "fhi-xpqa" -installation (v7.0.1), snapshots stopped working, the following exception is given:

```
2019-08-12 09:14:17,017 ERROR s.r.enonic.datatoolbox.RcdScriptBean - Error while creating snapshot
org.elasticsearch.common.breaker.CircuitBreakingException: [parent] Data too large, data for [<transport_request>] would be larger than limit of [719093760/685.7mb]
	at org.elasticsearch.indices.breaker.HierarchyCircuitBreakerService.checkParentLimit(HierarchyCircuitBreakerService.java:247)
	at org.elasticsearch.common.breaker.ChildMemoryCircuitBreaker.addEstimateBytesAndMaybeBreak(ChildMemoryCircuitBreaker.java:156)
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:214)
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:116)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

Research what this parent circuit breaker (https://www.elastic.co/guide/en/elasticsearch/reference/2.3/circuit-breaker.html#parent-circuit-breaker) is doing, why it triggers and what can be done.

Some notes:

* The fhi installation has a lot of repositories
* Needs access to EC-environment, ask @runarmyklebust  for installation / setup / walk-though

**Comment by runarmyklebust** [comment] 2019-09-10 08:11
Ok, I had a look, tried to figure out what message was causing this but it disappeared from each node after restart. Exposed the debug-port on all cluster-instances, lets debug when it happens again to try to pinpoint the exact event or message that is sent.

**Comment by rymsha** [comment] 2019-09-10 09:54
stack-trace points to `transport.inFlightRequestsBreaker().addEstimateBytesAndMaybeBreak(messageLengthBytes, "<transport_request>");` which uses `in_flight_requests` `CircuitBreaker`s 
they get configured by 
`network.breaker.inflight_requests.limit` and `network.breaker.inflight_requests.overhead`

https://www.elastic.co/guide/en/elasticsearch/reference/2.4/circuit-breaker.html#in-flight-circuit-breaker

It is an indicator that transport protocol message does not fit into ES node heap.

Since it happened on master node (where data is not transported to, I assume), I suspect event or task payload was too big to fit. (Event has Map which can be any size)

It may be good idea to make our own configurable Circuit Breaker, so events/tasks are never unbounded.

**Comment by runarmyklebust** [comment] 2019-11-11 08:50
We should do something about this; to be discussed

**Comment by rymsha** [comment] 2020-03-06 17:34
This also may be a consequence of enormous max_result_window we set https://github.com/enonic/xp/commit/00287ab169d2b930fa1b44a6a9c2e7c5fc484834

So, if master node queries data (to do a dump, for instance), data-node fetches it and sends full chunk to master. Master can't fit it into heap - circuit breaker prevents OutOfMemory

**Comment by rymsha** [comment] 2020-07-15 14:53
This may happen due to Elasticsearch overload, apparently.
https://discuss.elastic.co/t/should-circuitbreakingexception-cause-the-node-to-become-failed/220817

- is it a custom snapshot storage (like s3)?
- is snapshot storage fast enough to save snapshot data with the same or greater speed it arrives?

**Comment by rymsha** [comment] 2021-06-14 10:11
@gbbirkisson @hjelmevold can you confirm this bug is still reproducible?
If yes, please provide a stacktrace, if no - let's close this issue.

**Comment by gbbirkisson** [comment] 2021-06-14 10:19
I have not seen this since HZ was introduced.

**Closed** 2021-06-14 10:21 UTC
Labels: Bug, Can't Reproduce
