### ISSUE TITLE
Admin API getDescendantsOfContents should find children by id, not path

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#8575] opened 2020-12-23 10:26 UTC
`getDescendantsOfContents` in admin API now fetches child items by parent `path`, but it should use `id` instead. Current behaviour is the reason for [this bug](https://github.com/enonic/xp/issues/8435), when paths are different in the draft and master branches.

**Comment by rymsha** [comment] 2021-01-04 14:35
Related to #2711

**Comment by rymsha** [comment] 2021-01-04 15:52
new method:
`resolveForUnpublish`
accept set of content ids: `cids`
for each id in `cids` find descendance ids in draft: `dcids` <- (I would skip this step, as it is complex to explain why some unrelated items in muster suddenly get unpublished). 
for each id `cids` and `dcids` find ids and descendance ids in master: `unids`
return `unids`

`resolveForDelete`
is out of some, but the result is more complicated. Some content ids could be purely deleted, but some should be unpublished only. see #8559

**Comment by rymsha** [comment] 2021-01-14 09:53
Duplicate of #8435

**Closed by rymsha** 2021-01-14 09:53 UTC
Labels: Bug
