### ISSUE TITLE
Better error message for: Exception processing template

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#4762] opened 2017-04-03 12:08 UTC
This error message is not very helpful:

```
14:01:18.194 ERROR [THYMELEAF][qtp1677813844-847] Exception processing template "bring:/site/parts/messages/part.thymeleaf.widget.html": An error happened during template parsing (template: "bring:/site/parts/messages/part.thymeleaf.widget.html")
```

The actual error was the template used a data-th-replace on a thymeleaf fragment file which where not there.

**Comment by aro** [comment] 2018-11-15 08:40
Looks like a duplicate of this issue https://github.com/enonic/lib-thymeleaf/issues/5
Closing this issue, since Thymeleaf lib has been moved to a separate project.

**Closed by aro** 2018-11-15 08:40 UTC
Labels: Improvement
