### ISSUE TITLE
Resolve relative to wrong path

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6465] opened 2018-07-23 13:07 UTC
So I have a macro which imports the get function from a part.

In the part code the view file is resolved outside the get method.

Resolve fails because it tries to resolve relative to the macro path, rather than the part path.

Workaround: Since parts and macros is on the same level the resolve path can be prefixed with '../../parts/partname/'

**Comment by aro** [comment] 2018-09-07 11:46
I think the resolving works correctly, resolving is based on the current JS file.

If you want to use it from 2 different controllers, the best would be to extract the common logic to a separate library file (in the same app), and call it from both controllers. If it should use different views, pass it as a parameter to the library function.

I think it is not a bug, closing this issue.

**Closed** 2018-09-07 11:46 UTC
Labels: Bug
