### ISSUE TITLE
Issue Dialog - handle removed assignee

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5391] opened 2017-08-01 11:57 UTC
The cause of the issue: Content Studio not refreshed, when a user was removed.

1. add a user
2. add a content and create a issue
3. Assignee the issue to the user
4. go to users app and remove the user
5. open IssueDetailsDialog or UpdateIssueDialog
BUG: the user still displayed on the modal-dialogs
Refresh the Content Studio in the browser and open the dialog again - removed user is not displayed

**Comment by alansemenov** [comment] 2017-08-02 07:52
Correct behaviour is this: when an issue is in readonly mode, deleted assignees should still be shown, but in edit mode deleted users should not be in the selector's list. The reason is that it should always be possible to see who an issue was originally assigned to, even after the user was deleted. 
When an issue is saved, all deleted assignees must be unlinked from it. 
Since it's not possible to fetch display name/initials of a deleted user, apply 0.5 opacity to the black user circle, leave it empty and use user Id as a tooltip. This will make it obvious that the issue is assigned to a deleted user.

**Comment by sgauruseu** [comment] 2017-08-02 09:37
when 2 users were assigneed to the issue and one user has been removed, user-icon disappears on the DetailsIssue dialog:
![det](https://user-images.githubusercontent.com/3728712/28867635-63279dd4-777f-11e7-9bfd-8ffcd6dbff0b.png)

**Closed** 2017-10-18 11:56 UTC
